{"body":"{\"output\":\"Exception caught:\\n\\n   Error: The sky is falling\\n\\n    Time: Tue May 18 10:19:41 2010\\n  Client: 127.0.0.1 (localhost)\\n     URI: http://localhost/foo/crash_obj\\n  Method: GET\\n\\nPackage: TestApp::Controller::Foo\\n   Line: 36\\n   File: /home/jason/github/catalyst-plugin-errorCatcher-activemq-stomp/t/lib/TestApp/Controller/Foo.pm\\n\\n      32: \\n      33: sub crash_obj : Local {\\n      34:     my ( $self, $c ) = @_;\\n      35: \\n-->   36:     die TestApp::Exception->new;\\n      37: }\\n      38: \\n      39: sub crash_user : Local {\\n      40:     my ( $self, $c ) = @_;\\n\\n\\nOriginal Error:\\n\\nThe sky is falling\\n\\n\"}","destination":"test-message"}